# PANDAS
## - todays covered class topics
* filtering
* sorting
* useful methods
* group by
* merge

In [9]:
from typing import List, Dict, Any
import pandas as pd

student_data = [
        {'roll no': 101, 'name': 'Alice', 'father': 'John Doe', 'course': 'BSc Computer Science', 'date of admission': '2021-09-01', 'fee': 5000},
        {'roll no': 102, 'name': 'Bob', 'father': 'Michael Smith', 'course': 'BSc Mathematics', 'date of admission': '2021-09-05', 'fee': 4500},
        {'roll no': 103, 'name': 'Charlie', 'father': 'Robert Brown', 'course': 'BA English', 'date of admission': '2021-09-08', 'fee': 4000},
        {'roll no': 104, 'name': 'David', 'father': 'James Wilson', 'course': 'BBA', 'date of admission': '2021-09-10', 'fee': 5500},
        {'roll no': 105, 'name': 'Eva', 'father': 'William Johnson', 'course': 'BCom', 'date of admission': '2021-09-12', 'fee': 4700},
        {'roll no': 106, 'name': 'Frank', 'father': 'George Clark', 'course': 'BSc Physics', 'date of admission': '2021-09-15', 'fee': 5100},
        {'roll no': 107, 'name': 'Grace', 'father': 'Henry Lewis', 'course': 'BSc Chemistry', 'date of admission': '2021-09-17', 'fee': 4800},
        {'roll no': 108, 'name': 'Hannah', 'father': 'Charles Harris', 'course': 'BBA', 'date of admission': '2021-09-20', 'fee': 5500},
        {'roll no': 109, 'name': 'Ivy', 'father': 'Joseph Martin', 'course': 'BSc Biology', 'date of admission': '2021-09-22', 'fee': 4900},
        {'roll no': 110, 'name': 'Jake', 'father': 'David Thomas', 'course': 'BA History', 'date of admission': '2021-09-25', 'fee': 4600}
    ]


student_df = pd.DataFrame(student_data)
student_df['date of admission'] = pd.to_datetime(student_df['date of admission'])
student_df

,roll no,name,father,course,date of admission,fee
0,101,Alice,John Doe,BSc Computer Science,2021-09-01,5000
1,102,Bob,Michael Smith,BSc Mathematics,2021-09-05,4500
2,103,Charlie,Robert Brown,BA English,2021-09-08,4000
3,104,David,James Wilson,BBA,2021-09-10,5500
4,105,Eva,William Johnson,BCom,2021-09-12,4700
5,106,Frank,George Clark,BSc Physics,2021-09-15,5100
6,107,Grace,Henry Lewis,BSc Chemistry,2021-09-17,4800
7,108,Hannah,Charles Harris,BBA,2021-09-20,5500
8,109,Ivy,Joseph Martin,BSc Biology,2021-09-22,4900
9,110,Jake,David Thomas,BA History,2021-09-25,4600

In [24]:
from typing import List, Dict, Any
import pandas as pd
import pandera as pa
from pandera import Column, DataFrameSchema, Check

# Define the student data
student_data = [
    {'roll no': 101, 'name': 'Alice', 'father': 'John Doe', 'course': 'BSc Computer Science', 'date of admission': '2021-09-01', 'fee': 5000},
    {'roll no': 102, 'name': 'Bob', 'father': 'Michael Smith', 'course': 'BSc Mathematics', 'date of admission': '2021-09-05', 'fee': 4500},
    {'roll no': 103, 'name': 'Charlie', 'father': 'Robert Brown', 'course': 'BA English', 'date of admission': '2021-09-08', 'fee': 4000},
    {'roll no': 104, 'name': 'David', 'father': 'James Wilson', 'course': 'BBA', 'date of admission': '2021-09-10', 'fee': 5500},
    {'roll no': 105, 'name': 'Eva', 'father': 'William Johnson', 'course': 'BCom', 'date of admission': '2021-09-12', 'fee': 4700},
    {'roll no': 106, 'name': 'Frank', 'father': 'George Clark', 'course': 'BSc Physics', 'date of admission': '2021-09-15', 'fee': 5100},
    {'roll no': 107, 'name': 'Grace', 'father': 'Henry Lewis', 'course': 'BSc Physics' , 'date of admission': '2021-09-17', 'fee': 4800},
    {'roll no': 108, 'name': 'Hannah', 'father': 'Charles Harris', 'course': 'BBA', 'date of admission': '2021-09-20', 'fee': 5500},
    {'roll no': 109, 'name': 'Ivy', 'father': 'Joseph Martin', 'course': 'BSc Biology', 'date of admission': '2021-09-22', 'fee': 4900},
    {'roll no': 110, 'name': 'Jake', 'father': 'David Thomas', 'course': 'BA History', 'date of admission': '2021-09-25', 'fee': 4600}
]

# Create a DataFrame
student_df = pd.DataFrame(student_data)
student_df['date of admission'] = pd.to_datetime(student_df['date of admission'])

# Define a Pandera schema for validation
schema = pa.DataFrameSchema({
    "roll no": Column(int, [Check.ge(100), Check.le(999)], nullable=False),  # Roll no between 100 and 999
    "name": Column(str, nullable=False),  # Name must be a string
    "father": Column(str, nullable=False),  # Father's name must be a string
    "course": Column(str, Check.isin(["BSc Computer Science", "BSc Mathematics", "BA English", "BBA", "BCom", "BSc Physics", "BSc Chemistry", "BSc Biology", "BA History"]), nullable=False),  # Course must be one of the provided options
    "date of admission": Column(pa.DateTime, nullable=False),  # Valid date format
    "fee": Column(int, [Check.ge(4000), Check.le(6000)], nullable=False)  # Fee between 4000 and 6000
})

# Validate the DataFrame
validated_df = schema.validate(student_df)
print(validated_df)

   roll no     name           father                course date of admission  \
0      101    Alice         John Doe  BSc Computer Science        2021-09-01
1      102      Bob    Michael Smith       BSc Mathematics        2021-09-05
2      103  Charlie     Robert Brown            BA English        2021-09-08
3      104    David     James Wilson                   BBA        2021-09-10
4      105      Eva  William Johnson                  BCom        2021-09-12
5      106    Frank     George Clark           BSc Physics        2021-09-15
6      107    Grace      Henry Lewis           BSc Physics        2021-09-17
7      108   Hannah   Charles Harris                   BBA        2021-09-20
8      109      Ivy    Joseph Martin           BSc Biology        2021-09-22
9      110     Jake     David Thomas            BA History        2021-09-25

    fee
0  5000
1  4500
2  4000
3  5500
4  4700
5  5100
6  4800
7  5500
8  4900
9  4600

## applying the filter function on the dataframe

In [30]:
student_df.course

0    BSc Computer Science
1         BSc Mathematics
2              BA English
3                     BBA
4                    BCom
5             BSc Physics
6             BSc Physics
7                     BBA
8             BSc Biology
9              BA History
Name: course, dtype: object

In [19]:
student_df.head(1)

   roll no   name    father                course date of admission   fee
0      101  Alice  John Doe  BSc Computer Science        2021-09-01  5000

In [20]:
student_df.course.value_counts()

course
BBA                     2
BSc Computer Science    1
BSc Mathematics         1
BA English              1
BCom                    1
BSc Physics             1
BSc Chemistry           1
BSc Biology             1
BA History              1
Name: count, dtype: int64

In [25]:
student_df.course.value_counts(dropna=False)  # dropna also shows us the null values

course
BBA                     2
BSc Physics             2
BSc Computer Science    1
BSc Mathematics         1
BA English              1
BCom                    1
BSc Biology             1
BA History              1
Name: count, dtype: int64

In [26]:
student_df.course.value_counts(dropna=False , normalize=True)

course
BBA                     0.2
BSc Physics             0.2
BSc Computer Science    0.1
BSc Mathematics         0.1
BA English              0.1
BCom                    0.1
BSc Biology             0.1
BA History              0.1
Name: proportion, dtype: float64

In [27]:
student_df.course.value_counts(dropna=False , normalize=True)*100

course
BBA                     20.0
BSc Physics             20.0
BSc Computer Science    10.0
BSc Mathematics         10.0
BA English              10.0
BCom                    10.0
BSc Biology             10.0
BA History              10.0
Name: proportion, dtype: float64

In [34]:
import pandas as pd
import numpy as np

# Create a sample fee transaction data
transaction_data = {
    'date': pd.date_range(start='2024-01-01', periods=10, freq='M'),  # 10 monthly transactions starting from 2024-01-01
    'fee': np.random.randint(4000, 6000, size=10)  # Random fee values between 4000 and 6000
}

# Create the DataFrame
transaction_df = pd.DataFrame(transaction_data)

# Display the DataFrame
print(transaction_df)

        date   fee
0 2024-01-31  5707
1 2024-02-29  4139
2 2024-03-31  5510
3 2024-04-30  5320
4 2024-05-31  4170
5 2024-06-30  5228
6 2024-07-31  4972
7 2024-08-31  5386
8 2024-09-30  4902
9 2024-10-31  5303

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8312\3307954645.py:6: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'date': pd.date_range(start='2024-01-01', periods=10, freq='M'),  # 10 monthly transactions starting from 2024-01-01

In [37]:
pd.cut(transaction_df.fee,
       [4000 ,5000 , 6000])

0    (5000, 6000]
1    (4000, 5000]
2    (5000, 6000]
3    (5000, 6000]
4    (4000, 5000]
5    (5000, 6000]
6    (4000, 5000]
7    (5000, 6000]
8    (4000, 5000]
9    (5000, 6000]
Name: fee, dtype: category
Categories (2, interval[int64, right]): [(4000, 5000] < (5000, 6000]]

In [38]:
pd.cut(transaction_df.fee,
       [4000 ,5000 , 6000]).value_counts()

fee
(5000, 6000]    6
(4000, 5000]    4
Name: count, dtype: int64

In [39]:
pd.cut(transaction_df.fee,
       [4000 ,5000 , 6000]).value_counts(normalize=True)*100

fee
(5000, 6000]    60.0
(4000, 5000]    40.0
Name: proportion, dtype: float64

In [40]:
pd.qcut(transaction_df.fee , [0.3 , .5,.7,.9 , 1])

0      (5529.7, 5707.0]
1                   NaN
2      (5339.8, 5529.7]
3      (5265.5, 5339.8]
4                   NaN
5    (4950.999, 5265.5]
6    (4950.999, 5265.5]
7      (5339.8, 5529.7]
8                   NaN
9      (5265.5, 5339.8]
Name: fee, dtype: category
Categories (4, interval[float64, right]): [(4950.999, 5265.5] < (5265.5, 5339.8] < (5339.8, 5529.7] < (5529.7, 5707.0]]

In [42]:
pd.qcut(transaction_df.fee , [0 , 0.3 , .5,.7,.9 , 1]).value_counts()

fee
(4138.999, 4951.0]    3
(4951.0, 5265.5]      2
(5265.5, 5339.8]      2
(5339.8, 5529.7]      2
(5529.7, 5707.0]      1
Name: count, dtype: int64

In [43]:
pd.qcut(transaction_df.fee , [0 , 0.3 , .5,.7,.9 , 1]).value_counts(normalize=True)*100

fee
(4138.999, 4951.0]    30.0
(4951.0, 5265.5]      20.0
(5265.5, 5339.8]      20.0
(5339.8, 5529.7]      20.0
(5529.7, 5707.0]      10.0
Name: proportion, dtype: float64

In [44]:
student_df.head()

,roll no,name,father,course,date of admission,fee
0,101,Alice,John Doe,BSc Computer Science,2021-09-01,5000
1,102,Bob,Michael Smith,BSc Mathematics,2021-09-05,4500
2,103,Charlie,Robert Brown,BA English,2021-09-08,4000
3,104,David,James Wilson,BBA,2021-09-10,5500
4,105,Eva,William Johnson,BCom,2021-09-12,4700

## filter on columns
Syntax:
```
dataframe[(dataframe.column1 == 'value1') & (dataframe.column2 == 'value2')]

```
* string columns
* numeric columns
* datetype columns

In [48]:
student_df

,roll no,name,father,course,date of admission,fee
0,101,Alice,John Doe,BSc Computer Science,2021-09-01,5000
1,102,Bob,Michael Smith,BSc Mathematics,2021-09-05,4500
2,103,Charlie,Robert Brown,BA English,2021-09-08,4000
3,104,David,James Wilson,BBA,2021-09-10,5500
4,105,Eva,William Johnson,BCom,2021-09-12,4700
5,106,Frank,George Clark,BSc Physics,2021-09-15,5100
6,107,Grace,Henry Lewis,BSc Physics,2021-09-17,4800
7,108,Hannah,Charles Harris,BBA,2021-09-20,5500
8,109,Ivy,Joseph Martin,BSc Biology,2021-09-22,4900
9,110,Jake,David Thomas,BA History,2021-09-25,4600

In [51]:
student_df['course'] == 'BSc Physics'

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7    False
8    False
9    False
Name: course, dtype: bool

In [53]:
student_df[student_df['course'] == 'BSc Physics']

   roll no   name        father       course date of admission   fee
5      106  Frank  George Clark  BSc Physics        2021-09-15  5100
6      107  Grace   Henry Lewis  BSc Physics        2021-09-17  4800

In [57]:
student_df[student_df['course'].str.lower() == 'bsc physics']

   roll no   name        father       course date of admission   fee
5      106  Frank  George Clark  BSc Physics        2021-09-15  5100
6      107  Grace   Henry Lewis  BSc Physics        2021-09-17  4800

In [58]:
student_df[student_df['course'].str.lower().str.contains('cs')]

   roll no   name         father           course date of admission   fee
1      102    Bob  Michael Smith  BSc Mathematics        2021-09-05  4500
5      106  Frank   George Clark      BSc Physics        2021-09-15  5100
6      107  Grace    Henry Lewis      BSc Physics        2021-09-17  4800

#### if there are two conditions or filters then:

In [11]:
student_df[(student_df['course'].str.lower().str.contains('cs')) & (student_df['fee']>= 4500 )]
# both conditions should be true

   roll no   name         father           course date of admission   fee
1      102    Bob  Michael Smith  BSc Mathematics        2021-09-05  4500
5      106  Frank   George Clark      BSc Physics        2021-09-15  5100
6      107  Grace    Henry Lewis      BSc Physics        2021-09-17  4800

In [9]:
student_df['course'].str.lower().str.contains('cs')  & student_df['fee']>= 4600

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [13]:
student_df

,roll no,name,father,course,date of admission,fee
0,101,Alice,John Doe,BSc Computer Science,2021-09-01,5000
1,102,Bob,Michael Smith,BSc Mathematics,2021-09-05,4500
2,103,Charlie,Robert Brown,BA English,2021-09-08,4000
3,104,David,James Wilson,BBA,2021-09-10,5500
4,105,Eva,William Johnson,BCom,2021-09-12,4700
5,106,Frank,George Clark,BSc Physics,2021-09-15,5100
6,107,Grace,Henry Lewis,BSc Physics,2021-09-17,4800
7,108,Hannah,Charles Harris,BBA,2021-09-20,5500
8,109,Ivy,Joseph Martin,BSc Biology,2021-09-22,4900
9,110,Jake,David Thomas,BA History,2021-09-25,4600

In [14]:
student_df['date of admission']

0   2021-09-01
1   2021-09-05
2   2021-09-08
3   2021-09-10
4   2021-09-12
5   2021-09-15
6   2021-09-17
7   2021-09-20
8   2021-09-22
9   2021-09-25
Name: date of admission, dtype: datetime64[ns]

## apply filter function on the columns
# syntax
`
dataframe.column.dt
`
## important function of date
* dt.strftime
* dt.strptime
```

The strftime() function in pandas, used with .dt accessor for datetime columns, follows the standard Python strftime format codes to represent dates and times. Here are all the symbols (format codes) that you can use with .dt.strftime() in pandas:

Date Components
%Y: Full year (e.g., 2023)
%y: Last two digits of the year (e.g., 23)
%m: Month as a zero-padded decimal (01 to 12)
%B: Full month name (e.g., January)
%b: Abbreviated month name (e.g., Jan)
%d: Day of the month as a zero-padded decimal (01 to 31)
%a: Abbreviated weekday name (e.g., Mon)
%A: Full weekday name (e.g., Monday)
%w: Weekday as a decimal number (0 for Sunday, 6 for Saturday)
%j: Day of the year as a zero-padded decimal (001 to 366)
%U: Week number of the year (Sunday as the first day of the week, 00 to 53)
%W: Week number of the year (Monday as the first day of the week, 00 to 53)
Time Components
%H: Hour (24-hour clock) as a zero-padded decimal (00 to 23)
%I: Hour (12-hour clock) as a zero-padded decimal (01 to 12)
%p: AM or PM
%M: Minute as a zero-padded decimal (00 to 59)
%S: Second as a zero-padded decimal (00 to 59)
%f: Microsecond as a decimal number (000000 to 999999)
%z: UTC offset in the form ±HHMM[SS] (e.g., +0000, -0400, +1030)
%Z: Time zone name (e.g., UTC, EST, CST)
Other Components
%c: Locale’s date and time (e.g., Mon Oct 23 14:30:59 2024)
%x: Locale’s date representation (e.g., 10/23/24 in the U.S.)
%X: Locale’s time representation (e.g., 14:30:59)

```

In [17]:
[i for i in dir(student_df['date of admission'].dt) if "_" not in i]

['ceil',
 'date',
 'day',
 'dayofweek',
 'dayofyear',
 'daysinmonth',
 'floor',
 'freq',
 'hour',
 'isocalendar',
 'microsecond',
 'minute',
 'month',
 'nanosecond',
 'normalize',
 'quarter',
 'round',
 'second',
 'strftime',
 'time',
 'timetz',
 'tz',
 'unit',
 'weekday',
 'year']

In [20]:
student_df['date of admission'].dt.year
student_df['date of admission'].dt.month
student_df['date of admission'].dt.date
student_df['date of admission'].dt.weekday

0    2
1    6
2    2
3    4
4    6
5    2
6    4
7    0
8    2
9    5
Name: date of admission, dtype: int32

In [30]:
from datetime import datetime
date : datetime = datetime.now()
date

datetime.datetime(2024, 10, 23, 1, 6, 8, 313428)

In [31]:
s1 = pd.Series(date)
s1

0   2024-10-23 01:06:08.313428
dtype: datetime64[ns]

In [35]:
s1.dt.strftime("%Y/%m/%d , %b , %B")

0    2024/10/23 , Oct , October
dtype: object

In [52]:
import pandas as pd

# Example Series with datetime values
s2 = pd.Series(pd.to_datetime(['2024-10-23', '2023-02-17', '2024-04-28']))
print(s2)

0   2024-10-23
1   2023-02-17
2   2024-04-28
dtype: datetime64[ns]

In [104]:
s2.dt.strftime("%Y/%m/%d , %b , %B")

0     2024/10/23 , Oct , October
1    2023/02/17 , Feb , February
2       2024/04/28 , Apr , April
dtype: object

# Group by
* In pandas, `groupby()` is a powerful method that allows you to group data based on some criteria and then apply functions (like sum, mean, count, etc.) to each group independently
* syntax: `groupby`
*  dataframe(['col1', 'col2', 'col3'])
*  dataframe(['col1', 'col2', 'col3']).aggregate([min  , max])
*  dataframe(['col1', 'col2', 'col3']).apply(function())

In [56]:
student_df

,roll no,name,father,course,date of admission,fee
0,101,Alice,John Doe,BSc Computer Science,2021-09-01,5000
1,102,Bob,Michael Smith,BSc Mathematics,2021-09-05,4500
2,103,Charlie,Robert Brown,BA English,2021-09-08,4000
3,104,David,James Wilson,BBA,2021-09-10,5500
4,105,Eva,William Johnson,BCom,2021-09-12,4700
5,106,Frank,George Clark,BSc Physics,2021-09-15,5100
6,107,Grace,Henry Lewis,BSc Physics,2021-09-17,4800
7,108,Hannah,Charles Harris,BBA,2021-09-20,5500
8,109,Ivy,Joseph Martin,BSc Biology,2021-09-22,4900
9,110,Jake,David Thomas,BA History,2021-09-25,4600

In [57]:
student_df.groupby(['course'])

In [58]:
list(student_df.groupby(['course']))

[(('BA English',),
     roll no     name        father      course date of admission   fee
  2      103  Charlie  Robert Brown  BA English        2021-09-08  4000),
 (('BA History',),
     roll no  name        father      course date of admission   fee
  9      110  Jake  David Thomas  BA History        2021-09-25  4600),
 (('BBA',),
     roll no    name          father course date of admission   fee
  3      104   David    James Wilson    BBA        2021-09-10  5500
  7      108  Hannah  Charles Harris    BBA        2021-09-20  5500),
 (('BCom',),
     roll no name           father course date of admission   fee
  4      105  Eva  William Johnson   BCom        2021-09-12  4700),
 (('BSc Biology',),
     roll no name         father       course date of admission   fee
  8      109  Ivy  Joseph Martin  BSc Biology        2021-09-22  4900),
 (('BSc Computer Science',),
     roll no   name    father                course date of admission   fee
  0      101  Alice  John Doe  BSc Computer Science        2021-09-01  5000),
 (('BSc Mathematics',),
     roll no name         father           course date of admission   fee
  1      102  Bob  Michael Smith  BSc Mathematics        2021-09-05  4500),
 (('BSc Physics',),
     roll no   name        father       course date of admission   fee
  5      106  Frank  George Clark  BSc Physics        2021-09-15  5100
  6      107  Grace   Henry Lewis  BSc Physics        2021-09-17  4800)]

In [60]:
list(student_df.groupby(['course']))[0][0]

('BA English',)

In [61]:
list(student_df.groupby(['course']))[0][1]

   roll no     name        father      course date of admission   fee
2      103  Charlie  Robert Brown  BA English        2021-09-08  4000

In [66]:
for group in list(student_df.groupby(['course'])):
    display(group[0])
    display(group[1])
    print("=========================================================================")

('BA English',)

   roll no     name        father      course date of admission   fee
2      103  Charlie  Robert Brown  BA English        2021-09-08  4000

=========================================================================

('BA History',)

   roll no  name        father      course date of admission   fee
9      110  Jake  David Thomas  BA History        2021-09-25  4600

=========================================================================

('BBA',)

   roll no    name          father course date of admission   fee
3      104   David    James Wilson    BBA        2021-09-10  5500
7      108  Hannah  Charles Harris    BBA        2021-09-20  5500

=========================================================================

('BCom',)

   roll no name           father course date of admission   fee
4      105  Eva  William Johnson   BCom        2021-09-12  4700

=========================================================================

('BSc Biology',)

   roll no name         father       course date of admission   fee
8      109  Ivy  Joseph Martin  BSc Biology        2021-09-22  4900

=========================================================================

('BSc Computer Science',)

   roll no   name    father                course date of admission   fee
0      101  Alice  John Doe  BSc Computer Science        2021-09-01  5000

=========================================================================

('BSc Mathematics',)

   roll no name         father           course date of admission   fee
1      102  Bob  Michael Smith  BSc Mathematics        2021-09-05  4500

=========================================================================

('BSc Physics',)

   roll no   name        father       course date of admission   fee
5      106  Frank  George Clark  BSc Physics        2021-09-15  5100
6      107  Grace   Henry Lewis  BSc Physics        2021-09-17  4800

=========================================================================

In [86]:
for group in list(student_df.groupby([student_df['date of admission'].dt.strftime("%Y"), 'course'])):
    display(group[0])  # This will display the grouping keys (year, course)
    
    display(group[1])  # This will display the grouped DataFrame
    print("=========================================================================")

('2021', 'BA English')

   roll no     name        father      course date of admission   fee
2      103  Charlie  Robert Brown  BA English        2021-09-08  4000

=========================================================================

('2021', 'BA History')

   roll no  name        father      course date of admission   fee
9      110  Jake  David Thomas  BA History        2021-09-25  4600

=========================================================================

('2021', 'BBA')

   roll no    name          father course date of admission   fee
3      104   David    James Wilson    BBA        2021-09-10  5500
7      108  Hannah  Charles Harris    BBA        2021-09-20  5500

=========================================================================

('2021', 'BCom')

   roll no name           father course date of admission   fee
4      105  Eva  William Johnson   BCom        2021-09-12  4700

=========================================================================

('2021', 'BSc Biology')

   roll no name         father       course date of admission   fee
8      109  Ivy  Joseph Martin  BSc Biology        2021-09-22  4900

=========================================================================

('2021', 'BSc Computer Science')

   roll no   name    father                course date of admission   fee
0      101  Alice  John Doe  BSc Computer Science        2021-09-01  5000

=========================================================================

('2021', 'BSc Mathematics')

   roll no name         father           course date of admission   fee
1      102  Bob  Michael Smith  BSc Mathematics        2021-09-05  4500

=========================================================================

('2021', 'BSc Physics')

   roll no   name        father       course date of admission   fee
5      106  Frank  George Clark  BSc Physics        2021-09-15  5100
6      107  Grace   Henry Lewis  BSc Physics        2021-09-17  4800

=========================================================================

In [87]:
student_df.groupby(['course']).aggregate('count')

                      roll no  name  father  date of admission  fee
course
BA English                  1     1       1                  1    1
BA History                  1     1       1                  1    1
BBA                         2     2       2                  2    2
BCom                        1     1       1                  1    1
BSc Biology                 1     1       1                  1    1
BSc Computer Science        1     1       1                  1    1
BSc Mathematics             1     1       1                  1    1
BSc Physics                 2     2       2                  2    2

In [93]:
student_df.groupby(['course'])['fee'].aggregate(['count', 'min', 'max'])

                      count   min   max
course
BA English                1  4000  4000
BA History                1  4600  4600
BBA                       2  5500  5500
BCom                      1  4700  4700
BSc Biology               1  4900  4900
BSc Computer Science      1  5000  5000
BSc Mathematics           1  4500  4500
BSc Physics               2  4800  5100

In [95]:
result = student_df.groupby(['course', student_df['date of admission'].dt.strftime("%B")])['fee'].aggregate(['count', 'min', 'max'])
print(result)

                                        count   min   max
course               date of admission
BA English           September              1  4000  4000
BA History           September              1  4600  4600
BBA                  September              2  5500  5500
BCom                 September              1  4700  4700
BSc Biology          September              1  4900  4900
BSc Computer Science September              1  5000  5000
BSc Mathematics      September              1  4500  4500
BSc Physics          September              2  4800  5100

In [102]:
student_df.groupby(['course']).apply(lambda x: x.head())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12228\1778018046.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  student_df.groupby(['course']).apply(lambda x: x.head())

                        roll no     name           father  \
course
BA English           2      103  Charlie     Robert Brown
BA History           9      110     Jake     David Thomas
BBA                  3      104    David     James Wilson
                     7      108   Hannah   Charles Harris
BCom                 4      105      Eva  William Johnson
BSc Biology          8      109      Ivy    Joseph Martin
BSc Computer Science 0      101    Alice         John Doe
BSc Mathematics      1      102      Bob    Michael Smith
BSc Physics          5      106    Frank     George Clark
                     6      107    Grace      Henry Lewis

                                      course date of admission   fee
course
BA English           2            BA English        2021-09-08  4000
BA History           9            BA History        2021-09-25  4600
BBA                  3                   BBA        2021-09-10  5500
                     7                   BBA        2021-09-20  5500
BCom                 4                  BCom        2021-09-12  4700
BSc Biology          8           BSc Biology        2021-09-22  4900
BSc Computer Science 0  BSc Computer Science        2021-09-01  5000
BSc Mathematics      1       BSc Mathematics        2021-09-05  4500
BSc Physics          5           BSc Physics        2021-09-15  5100
                     6           BSc Physics        2021-09-17  4800

In [112]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\lenovo\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.21 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lenovo\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [113]:
student_df.course.value_counts().plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [114]:
student_df.course.value_counts().plot(kind='bar')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [115]:
student_df.course.value_counts().plot(kind='pie')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [117]:
student_df.groupby(['course'])['fee'].aggregate(['count', 'min', 'max']).plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.